### ISSUE TITLE
Add Radboud UMC

### ISSUE THREAD

**Issue by luna-dj** [cvyl/awesome-transgender#7]
Hello,

There is also radboud umc for trnas healthcare

https://www.radboudumc.nl/expertisecentra/geslacht-en-gender/transgenderzorg

Could you add it?

**Comment by cvyl** [comment]
Solved in https://github.com/cvyl/awesome-transgender/pull/8

**Comment by cvyl** [comment]
Fixed in https://github.com/cvyl/awesome-transgender/commit/7d01da7655b983ce8cc4e6375b7079add8bb9765
